grafana:
  enabled: true
  service:
    type: ClusterIP

prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: false
  extraScrapeConfigs: |
    - job_name: key-value-store-server-metrics
      metrics_path: '/metrics'
      scrape_interval: 5s
      static_configs:
        - targets: ['key-value-store-server-metrics.keda:9001']
          labels:
            application: 'key-value-store-server'

loki:
  enabled: true
  image:
    tag: 2.9.3
  persistence:
    enabled: false
    # enabled: true
    # size: 1Gi

promtail:
    enabled: true
    config:
      clients:
        - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
