apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-value-store-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key-value-store-worker
      component: key-value-store-worker
  template:
    metadata:
      labels:
        app: key-value-store-worker
        component: key-value-store-worker
    spec:
      containers:
      - name: key-value-store-worker
        image: abhilakshsinghreen/k8s-key-value-store-worker:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: TASK_DELAY
          value: "0"
        envFrom:
        - configMapRef:
            name: key-value-store-redis-config
